-- changeset AngeloCrl:01_user
-- author: AngeloCrl

CREATE TABLE USER (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL_VERIFIED BOOLEAN DEFAULT 0 NOT NULL,
    CREATION_DATE DATETIME NOT NULL,
    LAST_MOD_DATE DATETIME NOT NULL,
    CONSTRAINT UK_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE USER_ROLE (
        ID BIGINT PRIMARY KEY AUTO_INCREMENT,
        ROLE VARCHAR(100) NOT NULL,
        USER_ID BIGINT,
        CONSTRAINT USER_ID_FK_IN_USER_ROLES_TABLE FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE
);

CREATE TABLE TOKEN (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TOKEN VARCHAR(150) NOT NULL,
    USER_ID BIGINT,
    USER_TOKEN_TYPE VARCHAR(100) NOT NULL,
    EXPIRY_DATE DATETIME NULL,
    CONSTRAINT USER_ID_FK_IN_USER_TOKEN_TABLE FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE
);

