-- changeset AngeloCrl:03_car.sql
-- author: AngeloCrl

CREATE TABLE CAR (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BRAND VARCHAR(10) NOT NULL,
    MODEL VARCHAR(10) NOT NULL,
    MANUFACTURER_ID BIGINT,
    OWNER_ID BIGINT,
    CREATION_DATE DATETIME,
    LAST_MOD_DATE DATETIME,
    CONSTRAINT MANUFACTURER_ID_FK FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER (ID),
    CONSTRAINT OWNER_ID_FK FOREIGN KEY (OWNER_ID) REFERENCES USER (ID)
);