spring.datasource.embedded.mysql.enable=true

# db
spring.datasource.url=jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1;MODE=MYSQL
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.h2.Driver

# hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.show-sql=true
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

# liquibase
#spring.liquibase.changeLog=classpath:db/changelog-master.yml
#logging.level.liquibase = INFO

#server.port=8080

# jwt secrets
security.jwt.token.secret-key=secret-key

# MySQL port
spring.datasource.embedded.mysql.port=3406

# MySQL Version
#spring.datasource.embedded.mysql.version=v5_7_latest
